version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: captrivia
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./backend
        target: /app
    command: go run ./cmd/main.go

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    environment:
      REACT_APP_BACKEND_URL: localhost:8080
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: captrivia
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules:
