apiVersion: apps/v1
kind: Deployment
metadata:
  name: captrivia-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captrivia-backend
  template:
    metadata:
      labels:
        app: captrivia-backend
    spec:
      containers:
        - name: captrivia-backend
          image: <ur-image>
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 200m
              memory: 1Gi
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: captrivia-backend-service
  annotations:
    cloud.google.com/backend-config: '{"default": "backendconfig-captrivia"}' # Associate the BackendConfig with the Service
spec:
  selector:
    app: captrivia-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
